[project]
name = "koogs-vid-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "accelerate>=1.14.0",
    "diffusers>=0.40.0",
    "ftfy>=6.3.1",
    "gguf>=0.19.0",
    "imageio[ffmpeg]>=2.37.4",
    "pillow>=12.3.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "transformers>=5.16.1",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
